a = input()
print(" " * 4 + a * 1)
print(" " * 3 + a * 3)
print(" " * 2 + a * 5)
print(" " * 3 + a * 3)
print(" " * 2 + a * 5)
print( " " * 1 + a * 7)
print( a * 9)
print(" " * 2 + a * 5)
print(" " * 1 + a * 7)
print( a * 9)
